version: 0.0
os: linux
files:
  - source: src/
    destination: /var/www/html
    permissions:
      - object: /var/www/html
      pattern: "**"
      owner: apache
      group: apache
      mode: 755
      type:
        - file
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      runas: root
  AfterInstall:
    - location: scripts/change_permissions.sh
      runas: root
